### PR TITLE
Update package to use latest Lato 2.015 font

### PR DESCRIPTION
**Pull request by rmacd**
Version number has been bumped to match the version on the font package.

### CODE REVIEW

**Comment by jamesward** [comment]
Thanks for the PR.  What do you think about forking this repo into a new `lato-font` WebJar?

**Comment by rmacd** [comment]
Agreed - plus it would make the package less ambiguous. 

Do you want me to update this PR with the new artifactId or how would you like to go about it?

**Comment by jamesward** [comment]
Cool. I created: https://github.com/webjars/lato-font

But, there isn't a git tag for the `2.015` release:
https://github.com/betsol/lato-font/releases

Not sure where I can get a stable version for that.

**Comment by rmacd** [comment]
Legend, thanks!

Yeah, I think the versions are all screwy ... the [font author's web site](http://www.latofonts.com/lato-free-fonts/#download) refers to the latest version as v2.015 but the betsol upstream inexplicably refers to a 3.x release... so I've just stuck with the author's versioning for now.

**Pull request closed without merging**
